webtalk_init -webtalk_dir /home/yangz0e/Desktop/top-k_FIFO/top-k.sim/sim_1/behav/xsim/xsim.dir/testbench_toplevel_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov 15 15:59:44 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211887999_1777552194_210720986_228" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "18a9940b-bffa-4d01-b807-ad09197e08dd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "323feb34700c4dc0ab197c3754e85260" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "25" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen Threadripper PRO 3975WX 32-Cores" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1983.964 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "540.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.37_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "188652_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2279218101 -regid "211887999_1777552194_210720986_228" -xml /home/yangz0e/Desktop/top-k_FIFO/top-k.sim/sim_1/behav/xsim/xsim.dir/testbench_toplevel_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/yangz0e/Desktop/top-k_FIFO/top-k.sim/sim_1/behav/xsim/xsim.dir/testbench_toplevel_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/yangz0e/Desktop/top-k_FIFO/top-k.sim/sim_1/behav/xsim/xsim.dir/testbench_toplevel_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
